module.exports={
    css:{
        loaderOptions:{
            scss:{
                prependData:`
                @import "@/assets/scss/variable.scss";
                `
            }
        }
    },
    devServer:{
        proxy:{
            '/api':{
                target:"http://localhost:8080",
                changeOrigin:true,
                pathRewrite:{
                    '^/api':'/mock'
                }
            }
        }
    }
}